### ISSUE TITLE
Adding book pictures for better references

### ISSUE THREAD

**Issue by urgetolearn** [anuragverma108/SwapReads#38] opened 2024-05-10 05:31 UTC
Hey @anuragverma108 
Adding a few pictures of cover pages in the "Literary Realms we've covered" section will bring more impact on readers as the visuals can enhance the user experience.
picture for reference:
![819cJtSxykL _AC_UF1000,1000_QL80_](https://github.com/anuragverma108/SwapReads/assets/131844481/820ff2aa-1696-48d8-bcf3-092a26120434)

Please assign me this issue under GSSOC'24

**Comment by anuragverma108** [comment] 2024-05-10 06:36
Assigned!

**Comment by anuragverma108** [comment] 2024-05-10 06:37
Open PR after doing the work. Also attavh before & after screenshots

**Comment by sahithinandikula** [comment] 2024-05-11 15:23
hey @anuragverma108 Can I also work on adding book pictures? I see that the issue is already assigned, but just wanted to confirm.

**Comment by anuragverma108** [comment] 2024-05-15 05:49
Any Updates @urgetolearn

**Comment by RitiChandak** [comment] 2024-05-30 14:22
@urgetolearn Any updates?

**Comment by abhibhande** [comment] 2024-05-31 08:32
@anuragverma108 can i work on this issue?

**Comment by RitiChandak** [comment] 2024-06-06 18:32
@abhibhande do you want to work on it??

**Comment by abhibhande** [comment] 2024-06-07 04:36
@RitiChandak yes !!

**Comment by RitiChandak** [comment] 2024-06-07 05:00
assigned to you

**Comment by abhibhande** [comment] 2024-06-07 09:35
### Before
![Screenshot 2024-06-07 104625](https://github.com/anuragverma108/SwapReads/assets/68599334/88569704-e14b-4fa7-90f2-25502d9f74b8)


### After Update

![Screenshot 2024-06-07 145657](https://github.com/anuragverma108/SwapReads/assets/68599334/5d5a4b6a-e396-4582-865d-49f825b8dcea)

**### After Hover On image**
![Screenshot 2024-06-07 145709](https://github.com/anuragverma108/SwapReads/assets/68599334/97e0f4cc-ec56-4558-89b3-551a5b5d689b)
![Screenshot 2024-06-07 145914](https://github.com/anuragverma108/SwapReads/assets/68599334/50a80dd4-166d-498f-bf89-ffee3d238014)


### Please review if it is okay then i will commit it

**Comment by RitiChandak** [comment] 2024-06-08 15:28
@anuragverma108 please review the design

**Comment by anuragverma108** [comment] 2024-06-08 15:32
@abhibhande @RitiChandak It is not looking good.

**Comment by abhibhande** [comment] 2024-06-09 11:55
Before Hover
![Screenshot 2024-06-09 172328](https://github.com/anuragverma108/SwapReads/assets/68599334/8a565824-09a1-4d1e-af3f-430b5b47c65d)

After Hover
![Uploading Screenshot 2024-06-09 172338.png…]()

Please view the design

**Closed** 2024-07-05 17:48 UTC
Labels: enhancement, good first issue, gssoc, overdue
